### ISSUE TITLE
Unable to build demo playlistplayer with Qt5.4

### ISSUE THREAD

**Issue by a-andreyev** [AlexandrePTJ/libmopiqy#2]
Archlinux x86_64, Qt 5.4.1-2 (Got qt-websockets 5.4 installed too):
`Cannot find -libmopiqy0` when building  demos/playlistplayer.
Main library without demos builds ok.

**Comment by AlexandrePTJ** [comment]
This has been corrected in dev branch. I just merge it in master, please pull and tell me.

**Comment by a-andreyev** [comment]
Sorry, didn't notice the dev branch previously! Thank you, dev branch compiles without problems!
